export const GET_DOCTOR_REQ = "GET_DOCTOR_REQ";
export const GET_DOCTOR_SUCCESS = "GET_DOCTOR_SUCCESS";
export const GET_DOCTOR_FAILURE = "GET_DOCTOR_FAILURE";
export const FILTER_DATA = "FILTER_DATA";

export const SEARCH_TERM = "SEARCH_TERM";

export const GET_CLICKED_DOCTOR_REQ = "GET_CLICKED_DOCTOR_REQ";
export const GET_CLICKED_DOCTOR_SUCCESS = "GET_CLICKED_DOCTOR_SUCCESS";
export const GET_CLICKED_DOCTOR_FAILURE = "GET_CLICKED_DOCTOR_FAILURE";




